INSERT INTO pictograma (nombre, icono, categoria_id) VALUES
('Comida',           'restaurant', 8),
('Agua',             'local-drink', 8),
('Baño',             'wc', 8),
('Dormir',           'bed', 8),
('Feliz',            'sentiment-satisfied-alt', 9),
('Triste',           'sentiment-dissatisfied', 9),
('Ansioso',          'sentiment-very-dissatisfied', 9),
('Dolor',            'sick', 9),
('Saludar',          'emoji-people', 10),
('Gracias',          'volunteer-activism', 10),
('Ayuda',            'help-outline', 10),
('Llamar',           'call', 10),
('Leer',             'menu-book', 11),
('Caminar',          'directions-walk', 11),
('Ver TV',           'tv', 11),
('Jugar',            'sports-esports', 11),
('Me gusta',         'thumb-up', 12),
('No me gusta',      'thumb-down', 12),
('Quiero más',       'add-circle-outline', 12),
('No quiero',        'remove-circle-outline', 12),
('Andador',          'accessibility', 13),
('Silla de ruedas',  'accessible', 13),
('Manta',            'king-bed', 13),
('Doc',              'medical-services', 13);